theme: jekyll-theme-leap-day
title: Graduac칩n XIX en directo
description: Cobertura del acto de graduaci칩n de la edici칩n XIX del M치ster en Periodismo BCN_NY
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
